repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black
        entry: "./.pre-commit-checks black ."
        language: system
        require_serial: true

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: "./.pre-commit-checks flake8"
        language: system
        require_serial: true

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./.pre-commit-checks mypy ."
        language: system
        require_serial: true

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: "./.pre-commit-checks isort ."
        language: system
        require_serial: true
